# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Distribute iOS build to Firebase App Distribution"
  lane :firebase_distribution do
    build_app(
      scheme: "Runner", # Replace with your app's scheme if it's different
      export_method: "ad-hoc" # For distributing builds outside the App Store
    )
    firebase_app_distribution(
      app: ENV['IOS_APP_ID'], # Firebase App ID from GitHub Secrets
      ##testers: ENV['TESTER_EMAILS'], # Tester emails from GitHub Secrets
      groups: ENV['TESTER_GROUPS'], # Tester groups from GitHub Secrets
      release_notes: "Distributed via Fastlane and GitHub Actions" # Custom release notes
    )
  end
end
