# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Ditrube the app to Firebase App Distribution"
  lane  :deploy_to_firebase do
    #sh "flutter build apk"
    firebase_app_distribution(
      app: "1:937281614957:android:7e8c8babbb470098e0bb64", # Replace with your Firebase Android app ID
      groups: "testers",
      release_notes: "This Fastlane Build",
      firebase_cli_token: "1//038pMeFSOh2CxCgYIARAAGAMSNwF-L9IrqRH7hyGiUeF-A2l3kjIlUhtq2M342k5O1jOV141gtcvyNuZkIXENIzA2ZpAyemh_6xw",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      android_artifact_type: "APK",
      debug: true

    )

  end
end
