name: Flutter CI/CD

on:
  push:
    branches:
      - main
     
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Use the required Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Our Test
        run: flutter test

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version  # Ensure Firebase CLI is installed

      - name: Debug - Check Service Account Key
        run: |
          echo "Checking Firebase Service Account Key..."
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | head -n 10  # Avoid printing entire key
          echo "${{ secrets.FIREBASE_AUTH_TOKEN }}" > /tmp/firebase-service-account.json
          ls -l /tmp/firebase-service-account.json  # Check file exists
          cat /tmp/firebase-service-account.json  # Ensure file content is correct

      - name: Set GOOGLE_APPLICATION_CREDENTIALS and Run Firebase Commands
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/firebase-service-account.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
          firebase --token ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Ensure valid token is being used

      - name: Build APK
        run: flutter build apk --release

      - name: Deploy to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app <your-app-id> \
            --groups "testers"