name: Flutter CI/CD

on:
  push:
    branches:
      - publish_to_fastlane_android
      
     
  pull_request:
    branches:
      - publish_to_fastlane_android
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Use the required Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Our Test
        run: flutter test

      - name: Install Firebase App Distribution plugin for Fastlane
        run: |
          cd android
          fastlane add_plugin firebase_app_distribution

      - name: Deploy to Firebase via Fastlane
        env:
          FIREBASE_APP_ID: ${{ secrets.APP_ID }}
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          cd android
          fastlane deploy_to_firebase
      
