name: Flutter CI/CD

on:
  push:
    branches:
      - main
     
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the Eclipse Temurin distribution
          java-version: '17'

      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Use the required Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Our Test
        run: flutter test

      # Step 6: Install Firebase CLI
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
          firebase --version  # Check Firebase CLI installation

      - name: Authenticate with Firebase using Service Account Key
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-service-account.json
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > /tmp/firebase-service-account.json
          firebase --token ${{ secrets.FIREBASE_AUTH_TOKEN }} # Try logging in using token (optional but sometimes needed)


      - name: Build APK
        run: flutter build apk --release


      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
        



      # Step 8: Deploy APK to Firebase App Distribution
      - name: Deploy to Firebase App Distribution
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:937281614957:android:7e8c8babbb470098e0bb64
