name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - publish_to_firebase
      - ios_branch
  pull_request:
    branches:
      - main
      - publish_to_firebase
      - ios_branch

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout My Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Install Flutter Version 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5' # Use the required Flutter version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Tests
      - name: Run Our Test
        run: flutter test

      # Step 5: Install CocoaPods
      - name: Install CocoaPods
        run: |
          brew install cocoapods
          pod install --project-directory=ios

      # Step 6: Setup Signing for iOS
      - name: Setup Signing for iOS
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.STAGING_BUILD_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision
          echo "${{ secrets.STAGING_BUILD_CERTIFICATE_BASE64 }}" | base64 --decode > ios_certificate.p12
          security import ios_certificate.p12 -P "${{ secrets.STAGING_P12_PASSWORD }}" -A

      # Step 7: Build iOS App (IPA)
      - name: Build IPA
        run: |
          flutter build ipa --release \
          --export-options-plist=ios/ExportOptions.plist

      # Step 8: Upload to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.IOS_APP_ID }} 
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          groups: testers
          file: build/ios/ipa/app.ipa

