name: Flutter CI/CD

# Trigger workflow on push to the main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flutter-test:
    name: Run Tests and Build Flutter App
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Flutter
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Step 4: Analyze the code
    - name: Run Flutter Analyze
      run: flutter analyze

    # Step 5: Run unit and widget tests
    - name: Run Flutter Tests
      run: flutter test

    # Step 6: Build APK for Android
    - name: Build Android APK
      run: flutter build apk --release

    # Step 7 (Optional): Build iOS app
    # Requires a macOS runner
    # Uncomment the following lines if iOS builds are needed
    # - name: Build iOS
    #   runs-on: macos-latest
    #   steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #   - name: Install Flutter
    #     uses: subosito/flutter-action@v2
    #     with:
    #       flutter-version: 'stable'
    #   - name: Install dependencies
    #     run: flutter pub get
    #   - name: Build iOS IPA
    #     run: flutter build ipa --release

    # Step 8 (Optional): Cache build outputs for faster builds
    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          build/
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
